### ISSUE TITLE
Unable to compile on Mac OS X 10.6.8

### ISSUE THREAD

**Issue by daFish** [spotify/echoprint-codegen#17]
I'm unable to compile codegen on Mac OS X 10.6.8 using Boost 1.46, TagLib 1.7 & ffmpeg 0.6.3

I get the following error running the make command:

``` bash
g++ -Wall -I/usr/local/include/boost-1_35 `taglib-config --cflags` -fPIC -O3 -DBOOST_UBLAS_NDEBUG -DNDEBUG -c -o AudioBufferInput.o AudioBufferInput.cxx
g++ -Wall -I/usr/local/include/boost-1_35 `taglib-config --cflags` -fPIC -O3 -DBOOST_UBLAS_NDEBUG -DNDEBUG -c -o AudioStreamInput.o AudioStreamInput.cxx
g++ -Wall -I/usr/local/include/boost-1_35 `taglib-config --cflags` -fPIC -O3 -DBOOST_UBLAS_NDEBUG -DNDEBUG -c -o Base64.o Base64.cxx
g++ -Wall -I/usr/local/include/boost-1_35 `taglib-config --cflags` -fPIC -O3 -DBOOST_UBLAS_NDEBUG -DNDEBUG -c -o Codegen.o Codegen.cxx
In file included from SubbandAnalysis.h:11,
                 from Codegen.h:18,
                 from Codegen.cxx:10:
MatrixUtility.h:12:43: error: boost/numeric/ublas/matrix.hpp: No such file or directory
MatrixUtility.h:13:48: error: boost/numeric/ublas/matrix_proxy.hpp: No such file or directory
In file included from SubbandAnalysis.h:11,
                 from Codegen.h:18,
                 from Codegen.cxx:10:
MatrixUtility.h:15: error: ‘boost’ has not been declared
MatrixUtility.h:15: error: ‘ublas’ is not a namespace-name
MatrixUtility.h:15: error: expected namespace-name before ‘;’ token
MatrixUtility.h:17: error: ‘ublas’ has not been declared
MatrixUtility.h:17: error: expected initializer before ‘<’ token
MatrixUtility.h:18: error: ‘ublas’ has not been declared
MatrixUtility.h:18: error: expected initializer before ‘<’ token
MatrixUtility.h:20: error: ‘ublas’ has not been declared
MatrixUtility.h:20: error: expected initializer before ‘<’ token
MatrixUtility.h:21: error: ‘ublas’ has not been declared
MatrixUtility.h:21: error: expected initializer before ‘<’ token
MatrixUtility.h:22: error: ‘ublas’ has not been declared
MatrixUtility.h:22: error: expected initializer before ‘<’ token
MatrixUtility.h:23: error: ‘ublas’ has not been declared
MatrixUtility.h:23: error: expected initializer before ‘<’ token
MatrixUtility.h:26: error: ‘MatrixUtility::rows’ declared as an ‘inline’ variable
MatrixUtility.h:26: error: ‘matrix_f’ was not declared in this scope
MatrixUtility.h:26: error: expected ‘,’ or ‘;’ before ‘{’ token
MatrixUtility.h:27: error: ‘MatrixUtility::cols’ declared as an ‘inline’ variable
MatrixUtility.h:27: error: ‘matrix_f’ was not declared in this scope
MatrixUtility.h:27: error: expected ‘,’ or ‘;’ before ‘{’ token
MatrixUtility.h:28: error: expected ‘,’ or ‘...’ before ‘&’ token
MatrixUtility.h:28: error: ISO C++ forbids declaration of ‘matrix_f’ with no type
MatrixUtility.h:29: error: expected ‘,’ or ‘...’ before ‘&’ token
MatrixUtility.h:29: error: ISO C++ forbids declaration of ‘matrix_f’ with no type
MatrixUtility.h:30: error: variable or field ‘clear’ declared void
MatrixUtility.h:30: error: ‘matrix_f’ was not declared in this scope
In file included from Codegen.h:18,
                 from Codegen.cxx:10:
SubbandAnalysis.h:51: error: ISO C++ forbids declaration of ‘matrix_f’ with no type
SubbandAnalysis.h:51: error: expected ‘;’ before ‘&’ token
SubbandAnalysis.h:53: error: expected `;' before ‘protected’
SubbandAnalysis.h:57: error: ‘matrix_f’ does not name a type
SubbandAnalysis.h:58: error: ‘matrix_f’ does not name a type
SubbandAnalysis.h:59: error: ‘matrix_f’ does not name a type
In file included from Codegen.h:19,
                 from Codegen.cxx:10:
Fingerprint.h:37: error: ‘matrix_u’ has not been declared
Codegen.cxx: In constructor ‘Codegen::Codegen(const float*, uint, int)’:
Codegen.cxx:20: error: ‘runtime_error’ is not a member of ‘std’
make: *** [Codegen.o] Error 1
```

Any suggestions about fixing this?
